sudo: required

language: java
jdk:
- openjdk8

services:
- docker

before_install:
- "docker pull levkuznetsov/rserve-ws"
- "docker run -d -p 8081:8081 levkuznetsov/rserve-ws"
- "docker ps -a"

script:
- mvn verify -Pit,cover

after_success:
  - mvn coveralls:report -Pcover
