sudo: required

language: java
jdk:
- openjdk8

services:
- docker

before_install:
- "docker pull levkuznetsov/rserve"
- "docker run -d -p 8081:8081 levkuznetsov/rserve-ws"
- "docker ps -a"

script:
- mvn verify -P it

after_success:
  - mvn coveralls:report
